### ISSUE TITLE
Mode in the list is not available to set.

### ISSUE THREAD

**Issue by ku-kueihsi** [avibrazil/RDM#1]
Maybe it is a better to ask the original author. 

I have 1280x800 HiDPI listed but I can not set it. I modified the code and get CGError 1007. I can not set 1280x720 HiDPI with two black bars on top and at bottom. I also have the same issue on another monitor. 840x525 HiDPI is listed but can be set.

Is it a upstream error of apple's api?

**Comment by avibrazil** [comment]
I have no idea. I'm just packaging the original software, almost unmodified.
