### ISSUE TITLE
HiDPI 16:9

### ISSUE THREAD

**Issue by NoobDoesMC** [avibrazil/RDM#18]
I use the 1920x1080 one atm to make my MacBook's screen 16:9, but it looks much lower resolution than APple's defaults. 

I'd like a HiDPI 16:9 option? Possible?

**Comment by avibrazil** [comment]
A MacBook is not physically shaped as 16:9.
If you put your screen resolution as 16:9 you'll waste pixels on top and bottom of your screen, which is a pity.
Use your whole screen as 1680×1050 (13") on HiDPI and let specific programs make specific content use only the 16:9 part of the screen they need. Example of programs that do that are Keynote, Powerpoint, movie players etc, depending on the content you give them to display.

**Comment by NoobDoesMC** [comment]
@avibrazil I made it 16:9 for recording my screen more easily with OBS, in _the_ standard resolution.

**Comment by avibrazil** [comment]
It is physically impossible for the LCD display to go 1920×1080 in HiDPI.
However, you can keep 16:9 aspect ratio with HiDPI if you set to 1280×720.
