### ISSUE TITLE
How to add 2048x1152

### ISSUE THREAD

**Issue by leocaseiro** [avibrazil/RDM#2]
Hi, thanks for sharing that, I'd like to use 2048x1152 resolution. Is that any chance to add it?

Thanks

**Comment by avibrazil** [comment]
Please remember that I don't develop RDM, just package it. So I don't intend to fix this.

As far as I understand, RDM should automatically detect the available resolutions. On my 13" I have 2048×1280 which uses the whole real estate of my screen. 2048×1152 is worse, at least on a 13".

**Comment by leocaseiro** [comment]
Hi @avibrazil, thanks for your reply.

I'm actually using a second monitor which is Samsung, not Apple. Unfortunately, my Samsung looks good only with 16:9, not 16:10.

No worries. I'm using a smaller res 1920x1200 for the time being.
