### ISSUE TITLE
Not really an issue, more like a question

### ISSUE THREAD

**Issue by postcatz** [avibrazil/RDM#3]
Hello,
I just wanted to know if it's possible to add custom resolutions. As I'm on my MacBook Air 11" i can't really use 1920x1080 cause the UI is too small. I'd like to add a 16:9 resolution between 1366x768 and 1440x900 - would that be possible? If yes, how?

Thanks in advantage!

**Comment by avibrazil** [comment]
Hello

I didn't write the actual code. Just the packaging and installation logic. What I know is that RDM auto detects your computer available resolutions. Maybe things have changed in macOS and RDM was not updates yet to reflect that.

**Comment by postcatz** [comment]
Hello,

thanks for you answer. I already downloaded SwitchresX. With SwitchresX i could implement my own resolution. Original at 1366x768, my custom is at1440x810. Sightly bigger but everything can be seen without any problems. Would totally recommend to everyone who's on a 11" MBA.
